goalmatrix/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.conf.urls import patterns, include, url
from goalmatrix import views
from django.conf.urls.i18n import i18n_patterns

urlpatterns = patterns('', 
	url(r'^employee/(?P<username>\w*)/$', views.showassignments, name='show_assingments'),
	url(r'^goal-matrix/(?P<username>\w*)/(?P<action>\w*)$', views.manage_goal_matrix, name='manage_goal_matrix'),
	url(r'^goal-matrix/update-goals$', views.update_goals, name='update_goals'),
	url(r'^team/(?P<team_short_name>[\w-]*)/$', views.show_team_employees, name='show_team_employees'),
	url(r'^goals/$', views.show_goals, name='show_goals'),
	)
#urlpatterns += i18n_patterns('', url(r'^index/$', 'views.index' , name='index'))


from django.conf import settings
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

rango/urls.py
#!/usr/bin/env python
# encoding: utf-8
from django.conf.urls import patterns, include, url
from rango import views

urlpatterns = patterns('', url(r'^$', views.index, name='index'),
	url(r'^about/', views.about, name='about'))

from django.conf import settings
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

tango_with_django_project/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
admin.autodiscover()
from rango import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tango_with_django_project.views.home', name='home'),
    # url(r'^tango_with_django_project/', include('tango_with_django_project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
	url(r'^rango/', include('rango.urls')),
    url(r'^goalmatrix/', include('goalmatrix.urls')),
    url(r'^versiontools/', include('versiontools.urls')),
)
urlpatterns += i18n_patterns('', url(r'^index/$', 'goalmatrix.views.index' , name='index'))
# At the top of your urls.py file, add the following line:
from django.conf import settings

# UNDERNEATH your urlpatterns definition, add the following two lines:
if settings.DEBUG:
	urlpatterns += patterns(
		'django.views.static',
		(r'media/(?P<path>.*)',
		'serve',
		{'document_root': settings.MEDIA_ROOT}), )

goalmatrix/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator, MinValueValidator, MaxValueValidator

class Team(models.Model):
    name = models.CharField(max_length=50)
    short_name = models.CharField(max_length=10, unique=True)
    
    def __unicode__(self):
        return u"%s, %s" % (self.short_name, self.name,)

class Employee(models.Model):
    first_name = models.CharField(max_length=30)
    middle_name = models.CharField(max_length=30, blank=True, null=True)
    last_name = models.CharField(max_length=30)
    username = models.CharField(max_length=30,unique=True)
    company_id = models.CharField(max_length=8, 
                                  validators=[RegexValidator(
                                            regex='^\d{7}$', message='company id must be 7 digits', 
                                            code='invalid_company_id'),],
                                  unique=True)
    team = models.ForeignKey(Team, null=True, blank=True)
    
    def total_assignment(self):
        ta = 0
        for assign in self.assignment_set.all():
            ta += assign.weight
            #print "ddddddddddddddddd %d" % (ta)
        return ta
    
    def assignment_grade(self):
        grade = 0
        for assign in self.assignment_set.all():
            grade += assign.grade
            #print "ddddddddddddddddd %d" % (ta)
        return grade

    def __unicode__(self):
        return u"%s, %s" % (self.last_name, self.first_name,)

class Goal(models.Model):
    position = models.IntegerField()
    description = models.CharField(max_length=120)
    grade = models.DecimalField(decimal_places=2, max_digits=5,
                                blank=True, null=True,
                                validators=[MinValueValidator(1),
                                            MaxValueValidator(100)])
    def has_all_acceptance_criteria(self):
        return self.acceptancecriteria_set.count() == 4
    
    class Meta:
        ordering = ['position']
    
    def __unicode__(self):
        return u"%d, %s" % (self.position, self.description)
    
class PersonalGoal(models.Model):
    position = models.IntegerField()
    employee = models.ForeignKey(Employee)
    description = models.CharField(max_length=120)
    weight = models.DecimalField(decimal_places=2, max_digits=5, 
                                blank=True, null=True,
                                validators=[MinValueValidator(1),
                                            MaxValueValidator(100)])
    grade = models.DecimalField(decimal_places=2, max_digits=5,
                                blank=True, null=True,
                                validators=[MinValueValidator(1),
                                            MaxValueValidator(100)])
    
   
class Assignment(models.Model):
    position = models.IntegerField()
    employee = models.ForeignKey(Employee)
    goal = models.ForeignKey(Goal)
    weight = models.DecimalField(decimal_places=2, max_digits=5, 
                                blank=True, null=True,
                                validators=[MinValueValidator(1),
                                            MaxValueValidator(100)])
    grade = models.DecimalField(decimal_places=2, max_digits=5,
                                blank=True, null=True,
                                validators=[MinValueValidator(1),
                                            MaxValueValidator(100)])
    class Meta:
        ordering = ['position']
        
class StandardClassification(models.Model):
    class Meta:
        ordering = ['-grade']
    STANDARD_CLASSIFICATION = (
                      ('O', 'Outstanding'),
                      ('E', 'Superior'),
                      ('S', 'Satisfactory'),
                      ('N', 'Needs Improvement'),
                      )
    letter = models.CharField(max_length=1,
                              choices=STANDARD_CLASSIFICATION,
                              primary_key=True)
    grade = models.DecimalField(decimal_places=2, max_digits=5)
    
    def __unicode__(self):
        return u'%s %d' % (self.letter, self.grade)
    
class AcceptanceCriteria(models.Model):
    goal = models.ForeignKey(Goal)
    
    DATE_DEFINITION_CHOICES =(('BEFORE', 'Before'), ('AFTER', 'After'), ('NA', 'Not Applicable'))
    standard = models.ForeignKey(StandardClassification)
    description = models.CharField(max_length=120, blank=True, null=True)
    date_definition = models.CharField(max_length=8, 
                                       choices = DATE_DEFINITION_CHOICES,
                                       default= DATE_DEFINITION_CHOICES[0][0])
    expected_date = models.DateField()
    expected_percentage = models.IntegerField(default=100)
    
    def __unicode__(self):
        if self.date_definition == 'BEFORE':
            return u"Terminar el %.0f%% antes del %s. (%s)" % (self.expected_percentage, self.expected_date.strftime('%d-%b-%Y'), self.standard,)
        elif self.date_definition == 'AFTER':
            return u"Terminar el %.0f%% despues del %s. (%s)" % (self.expected_percentage, self.expected_date.strftime('%d-%b-%Y'), self.standard,)
        else:
            return u"%s para %s avance %d fecha  %s" % (self.goal, self.standard, self.expected_percentage, self.expected_date)
    
class Deliverable(models.Model):
    position = models.IntegerField()
    goal = models.ForeignKey(Goal)
    description = models.CharField(max_length=120)
    

goalmatrix/views.py
from django.shortcuts import render_to_response
from goalmatrix.models import Employee, Team, Goal, Assignment
from django.template.context import RequestContext
import re
from decimal import Decimal
from django.utils.translation import ugettext as _
from django.http.response import HttpResponse


def index(request):
    # Translators: This message appears on the home page only
    output = _("No month specified")
    return HttpResponse(output)

def showassignments(request, username):
    employee = Employee.objects.get(username=username)
    #print "******************     %s        ***************************" % (employee.id)
    #print "******************     %s        ***************************" % (employee.total_assignment)
    context = RequestContext(request)
    
    context_dict = {'employee': employee}

    return render_to_response('goalmatrix/employee.html', context_dict, context)

def show_team_employees(request, team_short_name):
    team = Team.objects.get(short_name=team_short_name.upper())
    context = RequestContext(request)
    context_dict = {'team': team}

    return render_to_response('goalmatrix/team.html', context_dict, context)

def manage_goal_matrix(request, username, action):
    employee = Employee.objects.get(username=username)
    context = RequestContext(request)
    context_dict = {'employee': employee}
    if request.method == 'POST':
        message = update_goals(request)
        context_dict.update({'message' : message})
        
    return render_to_response('goalmatrix/goal-matrix-form.html', context_dict, context)
def show_goals(request):
    goals = Goal.objects.all()
    context = RequestContext(request)
    context_dict = {'goals': goals}
    return render_to_response('goalmatrix/goals.html', context_dict, context)
    
def update_goals(request):
    pattern = re.compile('grade-(\d*)$', re.UNICODE)
    ag_pattern = re.compile('assignment-grade-(\d*)$', re.UNICODE)
    goal_ids = {}
    assignment_ids={}
    for key, value in request.POST.iteritems():
        m = pattern.match(key)
        if m:
            goal_ids.update({m.group(1):value})
        ag_m = ag_pattern.match(key)
        if ag_m:
            assignment_ids.update({ag_m.group(1):value})
    goals = Goal.objects.filter(id__in = goal_ids.keys())
    assignments = Assignment.objects.filter(id__in=assignment_ids.keys())
    goal_count=0
    assignment_count=0
    for goal in goals:
        uni_goal_id = unicode(goal.id)
        #gg = goal.grade
        #ggn = Decimal(goal_ids[uni_goal_id])
        #raise Exception("Ee")
        if goal_ids[uni_goal_id] == u'None' or len(goal_ids[uni_goal_id]) == 0 :
            goal_count += 1
            goal.grade = None
            goal.save()
        else :
            if goal.grade != Decimal(goal_ids[uni_goal_id]):
                goal_count += 1
                goal.grade = goal_ids[uni_goal_id]
                goal.save()
    for assignment in assignments:
        uni_assignment_id = unicode(assignment.id)
        if assignment_ids[uni_assignment_id] == u'None' or len(assignment_ids[uni_assignment_id]) == 0:
            assignment_count += 1
            assignment.grade = None
            assignment.save()
        else :
            if assignment.grade != Decimal(assignment_ids[uni_assignment_id]):
                assignment_count += 1
                assignment.grade = assignment_ids[uni_assignment_id]
                assignment.save()
            
    #goal_ids.append(('url', request.build_absolute_uri()))
    #return HttpResponse(goal_ids)
    #return manage_goal_matrix(request, request.POST.get('username'), 'edit', message=goal_ids)
    return "Updated %d goals, %d assignments" % (goal_count , assignment_count)
            
            
            

templates/goalmatrix/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">
{% load static %} <!-- New line -->
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	 <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}My amazing site{% endblock %}</title>
	<!-- CSS -->
	<link rel="stylesheet" href="{% static "css/goalmatrix.css" %}" /> 
	<link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css" %}" /> 
	<!-- JavaScript -->
	<script src="{% static "js/jquery-1.10.2.min.js" %}"></script> 
	<script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script> 
	<script src="{% static "js/goal-matrix.js" %}"></script> 
	
	<meta name="generator" content="TextMate http://macromates.com/">
	<meta name="author" content="Luis C. Berrocal">
	<!-- Date: 2013-10-20 -->
</head>
	<body>
			<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Goal Matrix</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
 	   <li><a href="{% url 'show_goals' %}">Goals</a></li>
      <li class="active"><a href="/admin/">Admin</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Team <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'show_team_employees' 'tino-ns'%}">Members TINO-NS</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
    </ul>
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
</div>
		    <div class="container">
		        {% block content %}{% endblock %}
		    </div>
	</body>
</html>

templates/goalmatrix/employee.html
{% extends "goalmatrix/base.html" %}
{% load static %} 
{% block title %}Employee Matrix{% endblock %}

{% block content %}
	<div class='acp'>Autoridad del Canal de Panamá</div>
	<div class='acp'>Matriz de Cumplimiento de Objetivos de Evaluación de Desempeño AF2014</div>
	<div class='acp'>Período: 01-oct-2013 al 30-sept-2014</div>
	<div class='employee-name'>{{ employee }} IP: {{ employee.company_id }}</div>
	<table id="matrix">
		<thead>
			<tr>
				<td rowspan='2'>Objetivo</td>
				<td colspan='4'>Estándares de Desempeño</td>
				<td rowspan='2'>Peso</td>
				<td rowspan='2'>Entregables</td>
			</tr>
			<tr>
				<td>Sobresaliente (O)</td>
				<td>Superior (E)</td>
				<td>Satisfactorio (S)</td>
				<td>Necesita mejorar (N)</td>				
			</tr>
		</thead>
	{% for assignment in employee.assignment_set.all %}
		<tr class="goal">
			<td class="goal-description">{{ assignment.goal.description}}</td>
			{% for criteria in assignment.goal.acceptancecriteria_set.all%}
			<td class="goal-criteria">{{ criteria }}</td>
			{% endfor%}
			<td class="goal-weight">{{ assignment.weight}}%</td>
			<td class="goal-deliverable">
				<ol>
					{% for deliverable in assignment.goal.deliverable_set.all %}
					<li>{{ deliverable.description }}</li>
					{% endfor %}
				</ol>
			</td>
		</tr>
	{% endfor %}
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>{{ employee.total_assignment }}%</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td>Firma</td>
		<td colspan='3'>&nbsp;</td>		
		<td>Fecha</td>
		<tdcolspan='2'>&nbsp;</td>
	</tr>
	</table>
{% endblock %}

templates/goalmatrix/goal-matrix-form.html
{% extends "goalmatrix/base.html" %}
{% load static %} 
{% block title %}Employee Matrix{% endblock %}

{% block content %}
	 <script>
		$( document ).ready(function() {
			calculate_grade();
			$("td.goal-grade > div.input-group > input").change(function(){
				calculate_grade();
			});
		});
	</script>
	<div>{{ employee }} {{ employee.company_id }}</div>
	<div><a href="{% url 'show_team_employees' employee.team.short_name %}" > {{employee.team.short_name}} </a></div>
	{% if message %}
		<div class="message">{{ message }}</div>
	{% endif%}
	<form action="{% url 'manage_goal_matrix' employee.username  'update_goals'  %}" method="post" id="frm-goal-matrix">
		{% csrf_token %}
		<input type="hidden" name="username" value="{{ employee.username }}" />
	<table id="matrix">
		<thead>
			<tr>
				<td>Objetivo</td>
				<td>O</td>
				<td>E</td>
				<td>S</td>
				<td>N</td>
				<td>Peso</td>
				<td>Nota del Objetivo</td>
				<td>Nota</td>
				<td>Entregables</td>
			</tr>
		</thead>
		<tbody>
	{% for assignment in employee.assignment_set.all %}
		<tr class="goal">
			<td class="goal-description">{{ assignment.goal.description}}</td>
			{% if assignment.goal.acceptancecriteria_set.count == 4 %}
			{% for criteria in assignment.goal.acceptancecriteria_set.all%}
			<td class="goal-criteria">{{ criteria }}</td>
			{% endfor%}
			{% else %}
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			{% endif%}
			<td class="goal-weight">{{ assignment.weight}}%</td>
			<td class="goal-grade">
				<!--<input type="text" name="grade-{{assignment.goal.id}}" value="{{ assignment.goal.grade}}">-->
				<div class="input-group input-group-sm">
				  <input type="text" class="form-control" placeholder="Goal Grade" 
				  	name="grade-{{assignment.goal.id}}" value="{{ assignment.goal.grade}}">
				  <span class="input-group-addon">%</span>
				</div>
			</td>
			<td class="goal-emp-grade">
				{{ employee.assignment.grade }}
				
			</td>
			<td class="goal-deliverable">
				<ol>
					{% for deliverable in assignment.goal.deliverable_set.all %}
					<li>{{ deliverable.description }}</li>
					{% endfor %}
				</ol>
				<input type="hidden" name="assignment-grade-{{assignment.id}}"
					 value="{{ employee.assignment.grade }}" />
			</td>
		</tr>
	{% endfor %}
	
	</tbody>
	<tfoot>
		<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>{{ employee.total_assignment }}%</td>
		<td>&nbsp;</td>
		<td id="employee-grade">&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	</tfoot>
	</table>
	 <!-- <input type="submit" value="Save" class="btn btn-primary"> -->
	 <button type="button" class="btn btn-primary" type="submit" onclick="calculate_grade(); document.getElementById('frm-goal-matrix').submit();">
  			<span class="glyphicon glyphicon-floppy-disk"></span>Guardar
	</button>

	</form>
{% endblock %}

templates/goalmatrix/goals.html
{% extends "goalmatrix/base.html" %}
{% load static %} 
{% block title %}Goals{% endblock %}

{% block content %}
	<h1>Goals</h1>
	<table id="goals" class="table table-bordered">
		<thead>
			<tr>
				<td>Objetivo</td>
				<td>O</td>
				<td>E</td>
				<td>S</td>
				<td>N</td>
				<td>Entregables</td>
				<td>Asignaciones</td>
			</tr>
		</thead>
	{% for goal in goals %}
		<tr class="goal">
			<td class="goal-description">{{ goal.description}}</td>
			{% for criteria in goal.acceptancecriteria_set.all%}
			<td class="goal-criteria">{{ criteria }}</td>
			{% endfor%}
			<td class="goal-deliverable">
				<ol>
					{% for deliverable in goal.deliverable_set.all %}
					<li>{{ deliverable.description }}</li>
					{% endfor %}
				</ol>
			</td>
			<td>
				<ol>
					{% for assign in goal.assignment_set.all %}
					<li>{{ assign.employee }} ({{ assign.weight}}%)</li>
					{% endfor %}
				</ol>
			</td>
		</tr>
	{% endfor %}
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	
	</table>
{% endblock %}

templates/goalmatrix/team.html
{% extends "goalmatrix/base.html" %}
{% load static %} 
{% block title %}Employee Matrix{% endblock %}

{% block content %}
	<h1>{{ team.name }}</h1>
	<div class="employee-info-header">
			<div class="col-md-2">
				Employee
			</div>
			<div class="col-md-1">
				 Grade
			</div>
			<div class="col-md-9">
			 Actions
			</div>
		</div>
	{% for employee in team.employee_set.all %}
		<div class="employee-info">
			<div class="col-md-2">
				<a href="{% url 'show_assingments' employee.username %}"> {{ employee}}</a>
			</div>
			<div class="col-md-1">
				{{ employee.assignment_grade}}%
			</div>
			<div class="col-md-4">
			<a href="{% url 'manage_goal_matrix' employee.username  'edit' %}"> Editar Matriz</a>
			</div>
			<div class="col-md-5">
			<a href="{% url 'show_assingments' employee.username  %}"> Matriz</a>
			</div>
		</div>
	{% endfor %}
{% endblock %}